locales:
  en:
    name: Kongo Keyboards
    description: Mobile OS keyboards for the Kongo language from the Divvun group at UiT.
  nb:
    name: Kongo tastatur
    description: Mobiltastatur for Kongo fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
